<a href="https://colab.research.google.com/github/gapalfaro-cmyk/Proyecto-de-fin-de-modulo-8---Alfaro-Badillo-Cruz-Perez-Rupit/blob/main/Proyecto_Modulo_8-EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd # Manejo de datos en tablas
import numpy as np # Operaciones numéricas
import matplotlib.pyplot as plt  # Gráficas
import seaborn as sns  # Gráficas más avanzadas

In [2]:
# Importamos la información
df = pd.read_excel("MunicipiosSequia.xlsx")
df.head(10)

,CVE_CONCATENADA,CVE_ENT,CVE_MUN,NOMBRE_MUN,ENTIDAD,ORG_CUENCA*,CLV_OC,CON_CUENCA,CVE_CONC,2003-01-31 00:00:00,...,2026-04-30 00:00:00,2026-05-15 00:00:00,2026-05-31 00:00:00,2026-06-15 00:00:00,2026-06-30 00:00:00,2026-07-15 00:00:00,2026-07-31 00:00:00,2026-08-15 00:00:00,2026-08-31 00:00:00,2026-09-15 00:00:00
0,1001,1,1,Aguascalientes,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1002,1,2,Asientos,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1003,1,3,Calvillo,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1004,1,4,Cosío,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1005,1,5,Jesús María,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1006,1,6,Pabellón de Arteaga,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1007,1,7,Rincón de Romos,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1008,1,8,San José de Gracia,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1009,1,9,Tepezalá,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1010,1,10,El Llano,Aguascalientes,Lerma-Santiago-Pacífico,VIII,Rio Santiago,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(2478, 444)

In [4]:
df.columns

Index([  'CVE_CONCATENADA',           'CVE_ENT',           'CVE_MUN',
              'NOMBRE_MUN',           'ENTIDAD',       'ORG_CUENCA*',
                  'CLV_OC',        'CON_CUENCA',          'CVE_CONC',
       2003-01-31 00:00:00,
       ...
       2026-04-30 00:00:00, 2026-05-15 00:00:00, 2026-05-31 00:00:00,
       2026-06-15 00:00:00, 2026-06-30 00:00:00, 2026-07-15 00:00:00,
       2026-07-31 00:00:00, 2026-08-15 00:00:00, 2026-08-31 00:00:00,
       2026-09-15 00:00:00],
      dtype='object', length=444)

Como tenemos un DataFrame municipio x fecha de la base de datos original: **Monitor de Sequía CONAGUA**, limpiaremos la base para tener la info en municipio-mes, listo para EDA y modelado.

In [5]:
eda_cols=df.columns[:9]
print(eda_cols)

Index(['CVE_CONCATENADA', 'CVE_ENT', 'CVE_MUN', 'NOMBRE_MUN', 'ENTIDAD',
       'ORG_CUENCA*', 'CLV_OC', 'CON_CUENCA', 'CVE_CONC'],
      dtype='object')

Del mapa oficial de categorías, podemos renombrar las intensidades de sequia:

In [6]:
eda_severidad = {np.nan: 0, 'D0': 1, 'D1': 2, 'D2': 3, 'D3': 4, 'D4': 5}
print(eda_severidad)

eda_sev_labels = {0: 'Sin sequía', 1: 'D0 Anormalmente seco', 2: 'D1 Sequía Moderada', 3: 'D2 Sequía Severa',
                  4: 'D3 Sequía Extrema', 5: 'D4 Sequía Excepcional'}
print(eda_sev_labels)

{nan: 0, 'D0': 1, 'D1': 2, 'D2': 3, 'D3': 4, 'D4': 5}
{0: 'Sin sequía', 1: 'D0 Anormalmente seco', 2: 'D1 Sequía Moderada', 3: 'D2 Sequía Severa', 4: 'D3 Sequía Extrema', 5: 'D4 Sequía Excepcional'}

Transformamos las columnas de fecha en filas:

In [7]:
fecha_cols = [f for f in df.columns if f not in eda_cols]
print(fecha_cols)
print(f"{df.shape[0]} municipios, {len(fecha_cols)} columnas de fecha")

[datetime.datetime(2003, 1, 31, 0, 0), datetime.datetime(2003, 2, 28, 0, 0), datetime.datetime(2003, 3, 31, 0, 0), datetime.datetime(2003, 4, 30, 0, 0), datetime.datetime(2003, 5, 31, 0, 0), datetime.datetime(2003, 6, 30, 0, 0), datetime.datetime(2003, 7, 31, 0, 0), datetime.datetime(2003, 8, 31, 0, 0), datetime.datetime(2003, 9, 30, 0, 0), datetime.datetime(2003, 10, 31, 0, 0), datetime.datetime(2003, 11, 30, 0, 0), datetime.datetime(2003, 12, 31, 0, 0), datetime.datetime(2004, 1, 31, 0, 0), datetime.datetime(2004, 2, 29, 0, 0), datetime.datetime(2004, 3, 31, 0, 0), datetime.datetime(2004, 4, 30, 0, 0), datetime.datetime(2004, 5, 31, 0, 0), datetime.datetime(2004, 6, 30, 0, 0), datetime.datetime(2004, 7, 31, 0, 0), datetime.datetime(2004, 8, 31, 0, 0), datetime.datetime(2004, 9, 30, 0, 0), datetime.datetime(2004, 10, 31, 0, 0), datetime.datetime(2004, 11, 30, 0, 0), datetime.datetime(2004, 12, 31, 0, 0), datetime.datetime(2005, 1, 31, 0, 0), datetime.datetime(2005, 2, 28, 0, 0), datetime.datetime(2005, 3, 31, 0, 0), datetime.datetime(2005, 4, 30, 0, 0), datetime.datetime(2005, 5, 31, 0, 0), datetime.datetime(2005, 6, 30, 0, 0), datetime.datetime(2005, 7, 31, 0, 0), datetime.datetime(2005, 8, 31, 0, 0), datetime.datetime(2005, 9, 30, 0, 0), datetime.datetime(2005, 10, 31, 0, 0), datetime.datetime(2005, 11, 30, 0, 0), datetime.datetime(2005, 12, 31, 0, 0), datetime.datetime(2006, 1, 31, 0, 0), datetime.datetime(2006, 2, 28, 0, 0), datetime.datetime(2006, 3, 31, 0, 0), datetime.datetime(2006, 4, 30, 0, 0), datetime.datetime(2006, 5, 31, 0, 0), datetime.datetime(2006, 6, 30, 0, 0), datetime.datetime(2006, 7, 31, 0, 0), datetime.datetime(2006, 8, 31, 0, 0), datetime.datetime(2006, 9, 30, 0, 0), datetime.datetime(2006, 10, 31, 0, 0), datetime.datetime(2006, 11, 30, 0, 0), datetime.datetime(2006, 12, 31, 0, 0), datetime.datetime(2007, 1, 31, 0, 0), datetime.datetime(2007, 2, 28, 0, 0), datetime.datetime(2007, 3, 31, 0, 0), datetime.datetime(2007, 4, 30, 0, 0), datetime.datetime(2007, 5, 31, 0, 0), datetime.datetime(2007, 6, 30, 0, 0), datetime.datetime(2007, 7, 31, 0, 0), datetime.datetime(2007, 8, 31, 0, 0), datetime.datetime(2007, 9, 30, 0, 0), datetime.datetime(2007, 10, 31, 0, 0), datetime.datetime(2007, 11, 30, 0, 0), datetime.datetime(2007, 12, 31, 0, 0), datetime.datetime(2008, 1, 31, 0, 0), datetime.datetime(2008, 2, 29, 0, 0), datetime.datetime(2008, 3, 31, 0, 0), datetime.datetime(2008, 4, 30, 0, 0), datetime.datetime(2008, 5, 31, 0, 0), datetime.datetime(2008, 6, 30, 0, 0), datetime.datetime(2008, 7, 31, 0, 0), datetime.datetime(2008, 8, 31, 0, 0), datetime.datetime(2008, 9, 30, 0, 0), datetime.datetime(2008, 10, 31, 0, 0), datetime.datetime(2008, 11, 30, 0, 0), datetime.datetime(2008, 12, 31, 0, 0), datetime.datetime(2009, 1, 31, 0, 0), datetime.datetime(2009, 2, 28, 0, 0), datetime.datetime(2009, 3, 31, 0, 0), datetime.datetime(2009, 4, 30, 0, 0), datetime.datetime(2009, 5, 31, 0, 0), datetime.datetime(2009, 6, 30, 0, 0), datetime.datetime(2009, 7, 31, 0, 0), datetime.datetime(2009, 8, 31, 0, 0), datetime.datetime(2009, 9, 30, 0, 0), datetime.datetime(2009, 10, 31, 0, 0), datetime.datetime(2009, 11, 30, 0, 0), datetime.datetime(2009, 12, 31, 0, 0), datetime.datetime(2010, 1, 31, 0, 0), datetime.datetime(2010, 2, 28, 0, 0), datetime.datetime(2010, 3, 31, 0, 0), datetime.datetime(2010, 4, 30, 0, 0), datetime.datetime(2010, 5, 31, 0, 0), datetime.datetime(2010, 6, 30, 0, 0), datetime.datetime(2010, 7, 31, 0, 0), datetime.datetime(2010, 8, 31, 0, 0), datetime.datetime(2010, 9, 30, 0, 0), datetime.datetime(2010, 10, 31, 0, 0), datetime.datetime(2010, 11, 30, 0, 0), datetime.datetime(2010, 12, 31, 0, 0), datetime.datetime(2011, 1, 31, 0, 0), datetime.datetime(2011, 2, 28, 0, 0), datetime.datetime(2011, 3, 31, 0, 0), datetime.datetime(2011, 4, 30, 0, 0), datetime.datetime(2011, 5, 31, 0, 0), datetime.datetime(2011, 6, 30, 0, 0), datetime.datetime(2011, 7, 31, 0, 0), datetime.datetime(2011, 8, 31, 0, 0), datetime.datetime(2011, 9, 30, 0, 0), datetime.datetime(2011, 10, 31, 0, 0), datetime.datetime(2011, 11, 30, 0, 0), datetime.datetime(2011, 12, 31, 0, 0), datetime.datetime(2012, 1, 31, 0, 0), datetime.datetime(2012, 2, 29, 0, 0), datetime.datetime(2012, 3, 31, 0, 0), datetime.datetime(2012, 4, 30, 0, 0), datetime.datetime(2012, 5, 31, 0, 0), datetime.datetime(2012, 6, 30, 0, 0), datetime.datetime(2012, 7, 31, 0, 0), datetime.datetime(2012, 8, 31, 0, 0), datetime.datetime(2012, 9, 30, 0, 0), datetime.datetime(2012, 10, 31, 0, 0), datetime.datetime(2012, 11, 30, 0, 0), datetime.datetime(2012, 12, 31, 0, 0), datetime.datetime(2013, 1, 31, 0, 0), datetime.datetime(2013, 2, 28, 0, 0), datetime.datetime(2013, 3, 31, 0, 0), datetime.datetime(2013, 4, 30, 0, 0), datetime.datetime(2013, 5, 31, 0, 0), datetime.datetime(2013, 6, 30, 0, 0), datetime.datetime(2013, 7, 31, 0, 0), datetime.datetime(2013, 8, 31, 0, 0), datetime.datetime(2013, 9, 30, 0, 0), datetime.datetime(2013, 10, 31, 0, 0), datetime.datetime(2013, 11, 30, 0, 0), datetime.datetime(2013, 12, 31, 0, 0), datetime.datetime(2014, 1, 31, 0, 0), datetime.datetime(2014, 2, 15, 0, 0), datetime.datetime(2014, 2, 28, 0, 0), datetime.datetime(2014, 3, 15, 0, 0), datetime.datetime(2014, 3, 31, 0, 0), datetime.datetime(2014, 4, 15, 0, 0), datetime.datetime(2014, 4, 30, 0, 0), datetime.datetime(2014, 5, 15, 0, 0), datetime.datetime(2014, 5, 31, 0, 0), datetime.datetime(2014, 6, 15, 0, 0), datetime.datetime(2014, 6, 30, 0, 0), datetime.datetime(2014, 7, 15, 0, 0), datetime.datetime(2014, 7, 31, 0, 0), datetime.datetime(2014, 8, 15, 0, 0), datetime.datetime(2014, 8, 31, 0, 0), datetime.datetime(2014, 9, 15, 0, 0), datetime.datetime(2014, 9, 30, 0, 0), datetime.datetime(2014, 10, 15, 0, 0), datetime.datetime(2014, 10, 31, 0, 0), datetime.datetime(2014, 11, 15, 0, 0), datetime.datetime(2014, 11, 30, 0, 0), datetime.datetime(2014, 12, 15, 0, 0), datetime.datetime(2014, 12, 31, 0, 0), datetime.datetime(2015, 1, 15, 0, 0), datetime.datetime(2015, 1, 31, 0, 0), datetime.datetime(2015, 2, 15, 0, 0), datetime.datetime(2015, 2, 28, 0, 0), datetime.datetime(2015, 3, 15, 0, 0), datetime.datetime(2015, 3, 31, 0, 0), datetime.datetime(2015, 4, 15, 0, 0), datetime.datetime(2015, 4, 30, 0, 0), datetime.datetime(2015, 5, 15, 0, 0), datetime.datetime(2015, 5, 31, 0, 0), datetime.datetime(2015, 6, 15, 0, 0), datetime.datetime(2015, 6, 30, 0, 0), datetime.datetime(2015, 7, 15, 0, 0), datetime.datetime(2015, 7, 31, 0, 0), datetime.datetime(2015, 8, 15, 0, 0), datetime.datetime(2015, 8, 31, 0, 0), datetime.datetime(2015, 9, 15, 0, 0), datetime.datetime(2015, 9, 30, 0, 0), datetime.datetime(2015, 10, 15, 0, 0), datetime.datetime(2015, 10, 31, 0, 0), datetime.datetime(2015, 11, 15, 0, 0), datetime.datetime(2015, 11, 30, 0, 0), datetime.datetime(2015, 12, 15, 0, 0), datetime.datetime(2015, 12, 31, 0, 0), datetime.datetime(2016, 1, 15, 0, 0), datetime.datetime(2016, 1, 31, 0, 0), datetime.datetime(2016, 2, 15, 0, 0), datetime.datetime(2016, 2, 29, 0, 0), datetime.datetime(2016, 3, 15, 0, 0), datetime.datetime(2016, 3, 31, 0, 0), datetime.datetime(2016, 4, 15, 0, 0), datetime.datetime(2016, 4, 30, 0, 0), datetime.datetime(2016, 5, 15, 0, 0), datetime.datetime(2016, 5, 31, 0, 0), datetime.datetime(2016, 6, 15, 0, 0), datetime.datetime(2016, 6, 30, 0, 0), datetime.datetime(2016, 7, 15, 0, 0), datetime.datetime(2016, 7, 31, 0, 0), datetime.datetime(2016, 8, 15, 0, 0), datetime.datetime(2016, 8, 31, 0, 0), datetime.datetime(2016, 9, 15, 0, 0), datetime.datetime(2016, 9, 30, 0, 0), datetime.datetime(2016, 10, 15, 0, 0), datetime.datetime(2016, 10, 31, 0, 0), datetime.datetime(2016, 11, 15, 0, 0), datetime.datetime(2016, 11, 30, 0, 0), datetime.datetime(2016, 12, 15, 0, 0), datetime.datetime(2016, 12, 31, 0, 0), datetime.datetime(2017, 1, 15, 0, 0), datetime.datetime(2017, 1, 31, 0, 0), datetime.datetime(2017, 2, 15, 0, 0), datetime.datetime(2017, 2, 28, 0, 0), datetime.datetime(2017, 3, 15, 0, 0), datetime.datetime(2017, 3, 31, 0, 0), datetime.datetime(2017, 4, 15, 0, 0), datetime.datetime(2017, 4, 30, 0, 0), datetime.datetime(2017, 5, 15, 0, 0), datetime.datetime(2017, 5, 31, 0, 0), datetime.datetime(2017, 6, 15, 0, 0), datetime.datetime(2017, 6, 30, 0, 0), datetime.datetime(2017, 7, 15, 0, 0), datetime.datetime(2017, 7, 31, 0, 0), datetime.datetime(2017, 8, 15, 0, 0), datetime.datetime(2017, 8, 31, 0, 0), datetime.datetime(2017, 9, 15, 0, 0), datetime.datetime(2017, 9, 30, 0, 0), datetime.datetime(2017, 10, 15, 0, 0), datetime.datetime(2017, 10, 31, 0, 0), datetime.datetime(2017, 11, 15, 0, 0), datetime.datetime(2017, 11, 30, 0, 0), datetime.datetime(2017, 12, 15, 0, 0), datetime.datetime(2017, 12, 31, 0, 0), datetime.datetime(2018, 1, 15, 0, 0), datetime.datetime(2018, 1, 31, 0, 0), datetime.datetime(2018, 2, 15, 0, 0), datetime.datetime(2018, 2, 28, 0, 0), datetime.datetime(2018, 3, 15, 0, 0), datetime.datetime(2018, 3, 31, 0, 0), datetime.datetime(2018, 4, 15, 0, 0), datetime.datetime(2018, 4, 30, 0, 0), datetime.datetime(2018, 5, 15, 0, 0), datetime.datetime(2018, 5, 31, 0, 0), datetime.datetime(2018, 6, 15, 0, 0), datetime.datetime(2018, 6, 30, 0, 0), datetime.datetime(2018, 7, 15, 0, 0), datetime.datetime(2018, 7, 31, 0, 0), datetime.datetime(2018, 8, 15, 0, 0), datetime.datetime(2018, 8, 31, 0, 0), datetime.datetime(2018, 9, 15, 0, 0), datetime.datetime(2018, 9, 30, 0, 0), datetime.datetime(2018, 10, 15, 0, 0), datetime.datetime(2018, 10, 31, 0, 0), datetime.datetime(2018, 11, 15, 0, 0), datetime.datetime(2018, 11, 30, 0, 0), datetime.datetime(2018, 12, 15, 0, 0), datetime.datetime(2018, 12, 31, 0, 0), datetime.datetime(2019, 1, 15, 0, 0), datetime.datetime(2019, 1, 31, 0, 0), datetime.datetime(2019, 2, 15, 0, 0), datetime.datetime(2019, 2, 28, 0, 0), datetime.datetime(2019, 3, 15, 0, 0), datetime.datetime(2019, 3, 31, 0, 0), datetime.datetime(2019, 4, 15, 0, 0), datetime.datetime(2019, 4, 30, 0, 0), datetime.datetime(2019, 5, 15, 0, 0), datetime.datetime(2019, 5, 31, 0, 0), datetime.datetime(2019, 6, 15, 0, 0), datetime.datetime(2019, 6, 30, 0, 0), datetime.datetime(2019, 7, 15, 0, 0), datetime.datetime(2019, 7, 31, 0, 0), datetime.datetime(2019, 8, 15, 0, 0), datetime.datetime(2019, 8, 31, 0, 0), datetime.datetime(2019, 9, 15, 0, 0), datetime.datetime(2019, 9, 30, 0, 0), datetime.datetime(2019, 10, 15, 0, 0), datetime.datetime(2019, 10, 31, 0, 0), datetime.datetime(2019, 11, 15, 0, 0), datetime.datetime(2019, 11, 30, 0, 0), datetime.datetime(2019, 12, 15, 0, 0), datetime.datetime(2019, 12, 31, 0, 0), datetime.datetime(2020, 1, 15, 0, 0), datetime.datetime(2020, 1, 31, 0, 0), datetime.datetime(2020, 2, 15, 0, 0), datetime.datetime(2020, 2, 29, 0, 0), datetime.datetime(2020, 3, 15, 0, 0), datetime.datetime(2020, 3, 31, 0, 0), datetime.datetime(2020, 4, 15, 0, 0), datetime.datetime(2020, 4, 30, 0, 0), datetime.datetime(2020, 5, 15, 0, 0), datetime.datetime(2020, 5, 31, 0, 0), datetime.datetime(2020, 6, 15, 0, 0), datetime.datetime(2020, 6, 30, 0, 0), datetime.datetime(2020, 7, 15, 0, 0), datetime.datetime(2020, 7, 31, 0, 0), datetime.datetime(2020, 8, 15, 0, 0), datetime.datetime(2020, 8, 31, 0, 0), datetime.datetime(2020, 9, 15, 0, 0), datetime.datetime(2020, 9, 30, 0, 0), datetime.datetime(2020, 10, 15, 0, 0), datetime.datetime(2020, 10, 31, 0, 0), datetime.datetime(2020, 11, 15, 0, 0), datetime.datetime(2020, 11, 30, 0, 0), datetime.datetime(2020, 12, 15, 0, 0), datetime.datetime(2020, 12, 31, 0, 0), datetime.datetime(2021, 1, 15, 0, 0), datetime.datetime(2021, 1, 31, 0, 0), datetime.datetime(2021, 2, 15, 0, 0), datetime.datetime(2021, 2, 28, 0, 0), datetime.datetime(2021, 3, 15, 0, 0), datetime.datetime(2021, 3, 31, 0, 0), datetime.datetime(2021, 4, 15, 0, 0), datetime.datetime(2021, 4, 30, 0, 0), datetime.datetime(2021, 5, 15, 0, 0), datetime.datetime(2021, 5, 31, 0, 0), datetime.datetime(2021, 6, 15, 0, 0), datetime.datetime(2021, 6, 30, 0, 0), datetime.datetime(2021, 7, 15, 0, 0), datetime.datetime(2021, 7, 31, 0, 0), datetime.datetime(2021, 8, 15, 0, 0), datetime.datetime(2021, 8, 31, 0, 0), datetime.datetime(2021, 9, 15, 0, 0), datetime.datetime(2021, 9, 30, 0, 0), datetime.datetime(2021, 10, 15, 0, 0), datetime.datetime(2021, 10, 31, 0, 0), datetime.datetime(2021, 11, 15, 0, 0), datetime.datetime(2021, 11, 30, 0, 0), datetime.datetime(2021, 12, 15, 0, 0), datetime.datetime(2021, 12, 31, 0, 0), datetime.datetime(2022, 1, 15, 0, 0), datetime.datetime(2022, 1, 31, 0, 0), datetime.datetime(2022, 2, 15, 0, 0), datetime.datetime(2022, 2, 28, 0, 0), datetime.datetime(2022, 3, 15, 0, 0), datetime.datetime(2022, 3, 31, 0, 0), datetime.datetime(2022, 4, 15, 0, 0), datetime.datetime(2022, 4, 30, 0, 0), datetime.datetime(2022, 5, 15, 0, 0), datetime.datetime(2022, 5, 31, 0, 0), datetime.datetime(2022, 6, 15, 0, 0), datetime.datetime(2022, 6, 30, 0, 0), datetime.datetime(2022, 7, 15, 0, 0), datetime.datetime(2022, 7, 31, 0, 0), datetime.datetime(2022, 8, 15, 0, 0), datetime.datetime(2022, 8, 31, 0, 0), datetime.datetime(2022, 9, 15, 0, 0), datetime.datetime(2022, 9, 30, 0, 0), datetime.datetime(2022, 10, 15, 0, 0), datetime.datetime(2022, 10, 31, 0, 0), datetime.datetime(2022, 11, 15, 0, 0), datetime.datetime(2022, 11, 30, 0, 0), datetime.datetime(2022, 12, 15, 0, 0), datetime.datetime(2022, 12, 31, 0, 0), datetime.datetime(2023, 1, 15, 0, 0), datetime.datetime(2023, 1, 31, 0, 0), datetime.datetime(2023, 2, 15, 0, 0), datetime.datetime(2023, 2, 28, 0, 0), datetime.datetime(2023, 3, 15, 0, 0), datetime.datetime(2023, 3, 31, 0, 0), datetime.datetime(2023, 4, 30, 0, 0), datetime.datetime(2023, 5, 15, 0, 0), datetime.datetime(2023, 5, 31, 0, 0), datetime.datetime(2023, 6, 15, 0, 0), datetime.datetime(2023, 6, 30, 0, 0), datetime.datetime(2023, 7, 15, 0, 0), datetime.datetime(2023, 7, 31, 0, 0), datetime.datetime(2023, 8, 15, 0, 0), datetime.datetime(2023, 8, 31, 0, 0), datetime.datetime(2023, 9, 15, 0, 0), datetime.datetime(2023, 9, 30, 0, 0), datetime.datetime(2023, 10, 15, 0, 0), datetime.datetime(2023, 10, 31, 0, 0), datetime.datetime(2023, 11, 15, 0, 0), datetime.datetime(2023, 11, 30, 0, 0), datetime.datetime(2023, 12, 15, 0, 0), datetime.datetime(2023, 12, 31, 0, 0), datetime.datetime(2024, 1, 15, 0, 0), datetime.datetime(2024, 1, 31, 0, 0), datetime.datetime(2024, 2, 15, 0, 0), datetime.datetime(2024, 2, 29, 0, 0), datetime.datetime(2024, 3, 15, 0, 0), datetime.datetime(2024, 3, 31, 0, 0), datetime.datetime(2024, 4, 15, 0, 0), datetime.datetime(2024, 4, 30, 0, 0), datetime.datetime(2024, 5, 15, 0, 0), datetime.datetime(2024, 5, 31, 0, 0), datetime.datetime(2024, 6, 15, 0, 0), datetime.datetime(2024, 6, 30, 0, 0), datetime.datetime(2024, 7, 15, 0, 0), datetime.datetime(2024, 7, 31, 0, 0), datetime.datetime(2024, 8, 15, 0, 0), datetime.datetime(2024, 8, 31, 0, 0), datetime.datetime(2024, 9, 15, 0, 0), datetime.datetime(2024, 9, 30, 0, 0), datetime.datetime(2024, 10, 15, 0, 0), datetime.datetime(2024, 10, 31, 0, 0), datetime.datetime(2024, 11, 15, 0, 0), datetime.datetime(2024, 11, 30, 0, 0), datetime.datetime(2024, 12, 15, 0, 0), datetime.datetime(2024, 12, 31, 0, 0), datetime.datetime(2025, 1, 15, 0, 0), datetime.datetime(2025, 1, 31, 0, 0), datetime.datetime(2025, 2, 15, 0, 0), datetime.datetime(2025, 2, 28, 0, 0), datetime.datetime(2025, 3, 15, 0, 0), datetime.datetime(2025, 3, 31, 0, 0), datetime.datetime(2025, 4, 15, 0, 0), datetime.datetime(2025, 4, 30, 0, 0), datetime.datetime(2025, 5, 15, 0, 0), datetime.datetime(2025, 5, 31, 0, 0), datetime.datetime(2025, 6, 15, 0, 0), datetime.datetime(2025, 6, 30, 0, 0), datetime.datetime(2025, 7, 15, 0, 0), datetime.datetime(2025, 7, 31, 0, 0), datetime.datetime(2025, 8, 15, 0, 0), datetime.datetime(2025, 8, 31, 0, 0), datetime.datetime(2025, 9, 15, 0, 0), datetime.datetime(2025, 9, 30, 0, 0), datetime.datetime(2025, 10, 15, 0, 0), datetime.datetime(2025, 10, 31, 0, 0), datetime.datetime(2025, 11, 15, 0, 0), datetime.datetime(2025, 11, 30, 0, 0), datetime.datetime(2025, 12, 15, 0, 0), datetime.datetime(2025, 12, 31, 0, 0), datetime.datetime(2026, 1, 15, 0, 0), datetime.datetime(2026, 1, 31, 0, 0), datetime.datetime(2026, 2, 15, 0, 0), datetime.datetime(2026, 2, 28, 0, 0), datetime.datetime(2026, 3, 15, 0, 0), datetime.datetime(2026, 3, 31, 0, 0), datetime.datetime(2026, 4, 15, 0, 0), datetime.datetime(2026, 4, 30, 0, 0), datetime.datetime(2026, 5, 15, 0, 0), datetime.datetime(2026, 5, 31, 0, 0), datetime.datetime(2026, 6, 15, 0, 0), datetime.datetime(2026, 6, 30, 0, 0), datetime.datetime(2026, 7, 15, 0, 0), datetime.datetime(2026, 7, 31, 0, 0), datetime.datetime(2026, 8, 15, 0, 0), datetime.datetime(2026, 8, 31, 0, 0), datetime.datetime(2026, 9, 15, 0, 0)]
2478 municipios, 435 columnas de fecha

Considerando que tenemos informacion desde el mes de enero de 2003, hasta septiembre de 2026 que es hasta donde está actualizada la base, deberíamos tener 12 columnas por año de 2003 a 2025 y 9 columnas de 2026, i.e., 12×23+9=285, pero tenemos muchas más. Veamos porqué sucede esto.

In [8]:
fechas_serie = pd.Series(fecha_cols)
print(fechas_serie)

0     2003-01-31
1     2003-02-28
2     2003-03-31
3     2003-04-30
4     2003-05-31
         ...
430   2026-07-15
431   2026-07-31
432   2026-08-15
433   2026-08-31
434   2026-09-15
Length: 435, dtype: datetime64[ns]

Notemos que las fechas en un inicio son a final de mes, pero en las ultimas fechas tenemos dos fechas por mes, es decir, la información mostrada es quincenal, ya no mensual.

In [9]:
conteo_anual = fechas_serie.dt.year.value_counts().sort_index()
print("Columnas de fecha por año: ")
print(conteo_anual)

Columnas de fecha por año:
2003    12
2004    12
2005    12
2006    12
2007    12
2008    12
2009    12
2010    12
2011    12
2012    12
2013    12
2014    23
2015    24
2016    24
2017    24
2018    24
2019    24
2020    24
2021    24
2022    24
2023    23
2024    24
2025    24
2026    17
Name: count, dtype: int64

---
Nuestra base cuenta con información de forma mensual en 2003-2013 (12 columnas/año) y de forma quincenal desde 2014 (~24 columnas/año). Para tener una base comparable en terminos de fechas, nos quedamos con la última lectura disponible de cada mes calendario (equivalente al cierre de mes que ya se usaba 2003-2013).

In [10]:
cols_mes = {}
for c in fecha_cols:
    key = (c.year, c.month)
    if key not in cols_mes or c > cols_mes[key]:
        cols_mes[key] = c
cierrem_cols = sorted(cols_mes.values())
print(f"{len(cierrem_cols)} periodos "
      f"({cierrem_cols[0].date()} a {cierrem_cols[-1].date()})")

285 periodos (2003-01-31 a 2026-09-15)

In [11]:
df_eda = df[list(eda_cols) + list(cierrem_cols)].copy()
print(df_eda.shape)
print(df_eda.columns)

(2478, 294)
Index([  'CVE_CONCATENADA',           'CVE_ENT',           'CVE_MUN',
              'NOMBRE_MUN',           'ENTIDAD',       'ORG_CUENCA*',
                  'CLV_OC',        'CON_CUENCA',          'CVE_CONC',
       2003-01-31 00:00:00,
       ...
       2025-12-31 00:00:00, 2026-01-31 00:00:00, 2026-02-28 00:00:00,
       2026-03-31 00:00:00, 2026-04-30 00:00:00, 2026-05-31 00:00:00,
       2026-06-30 00:00:00, 2026-07-31 00:00:00, 2026-08-31 00:00:00,
       2026-09-15 00:00:00],
      dtype='object', length=294)

In [12]:
# dejamos las variables de eda_cols como vienen en el DataFrame, pero vamos a pivotear las columnas de fecha con su
# clasificación de sequia, es decir, las columnas de fecha ahora serán filas y se crea la columna de clasificacion_sequia
# para cada fecha y municipio
# el número de filas del nuevo DataFrame corresponde al número de periodos (285) por cada entidad federativa (32) para cada
# municipio dentro de ellas (depende de la entidad).
df_clasif_municipio = df_eda.melt(id_vars=eda_cols, var_name='fecha', value_name='clasificacion_sequia')
df_clasif_municipio['fecha'] = pd.to_datetime(df_clasif_municipio['fecha'])
print(df_clasif_municipio)

        CVE_CONCATENADA  CVE_ENT  CVE_MUN             NOMBRE_MUN  \
0                  1001        1        1         Aguascalientes
1                  1002        1        2               Asientos
2                  1003        1        3               Calvillo
3                  1004        1        4                  Cosío
4                  1005        1        5            Jesús María
...                 ...      ...      ...                    ...
706225            32054       32       54          Villa Hidalgo
706226            32055       32       55             Villanueva
706227            32056       32       56              Zacatecas
706228            32057       32       57               Trancoso
706229            32058       32       58  Santa María de la Paz

               ENTIDAD                  ORG_CUENCA* CLV_OC     CON_CUENCA  \
0       Aguascalientes      Lerma-Santiago-Pacífico   VIII   Rio Santiago
1       Aguascalientes      Lerma-Santiago-Pacífico   VIII   Rio Santiago
2       Aguascalientes      Lerma-Santiago-Pacífico   VIII   Rio Santiago
3       Aguascalientes      Lerma-Santiago-Pacífico   VIII   Rio Santiago
4       Aguascalientes      Lerma-Santiago-Pacífico   VIII   Rio Santiago
...                ...                          ...    ...            ...
706225       Zacatecas  Cuencas Centrales Del Norte    VII  Del Altiplano
706226       Zacatecas      Lerma-Santiago-Pacífico   VIII   Rio Santiago
706227       Zacatecas      Lerma-Santiago-Pacífico   VIII   Rio Santiago
706228       Zacatecas  Cuencas Centrales Del Norte    VII  Del Altiplano
706229       Zacatecas      Lerma-Santiago-Pacífico   VIII   Rio Santiago

        CVE_CONC      fecha clasificacion_sequia
0             16 2003-01-31                  NaN
1             16 2003-01-31                  NaN
2             16 2003-01-31                  NaN
3             16 2003-01-31                  NaN
4             16 2003-01-31                  NaN
...          ...        ...                  ...
706225        14 2026-09-15                  NaN
706226        16 2026-09-15                  NaN
706227        16 2026-09-15                  NaN
706228        14 2026-09-15                  NaN
706229        16 2026-09-15                  NaN

[706230 rows x 11 columns]

In [27]:
# número de registros en NaN, es decir, municipios sin sequía en un periodo.
df_clasif_municipio['clasificacion_sequia'].isna().sum()

np.int64(410112)

In [28]:
# número de registros no vacíos, es decir con algun grado de sequía.
len(df_clasif_municipio)-df_clasif_municipio['clasificacion_sequia'].isna().sum()

np.int64(296118)

Mapeamos las intensidades para "eliminar" los nans, no es necesario imputarlos ya que por la naturaleza de la base los nan significa que no hay sequía.

In [23]:
df_clasif_municipio['intensidad'] = df_clasif_municipio['clasificacion_sequia'].map(eda_severidad)
df_clasif_municipio['intensidad']

0         0
1         0
2         0
3         0
4         0
         ..
706225    0
706226    0
706227    0
706228    0
706229    0
Name: intensidad, Length: 706230, dtype: int64

In [24]:
df_clasif_municipio['intensidad_desc'] = df_clasif_municipio['intensidad'].map(eda_sev_labels)
df_clasif_municipio['intensidad_desc']

0         Sin sequía
1         Sin sequía
2         Sin sequía
3         Sin sequía
4         Sin sequía
             ...
706225    Sin sequía
706226    Sin sequía
706227    Sin sequía
706228    Sin sequía
706229    Sin sequía
Name: intensidad_desc, Length: 706230, dtype: object

In [25]:
df_clasif_municipio['en_sequia'] = (df_clasif_municipio['intensidad'] >= 1).astype(int)
df_clasif_municipio['en_sequia']

0         0
1         0
2         0
3         0
4         0
         ..
706225    0
706226    0
706227    0
706228    0
706229    0
Name: en_sequia, Length: 706230, dtype: int64

In [26]:
df_clasif_municipio['intensidad'].sum()

np.int64(508638)

---

Nuestra base cuenta con información de forma mensual en 2003-2013 (12 columnas/año) y de forma quincenal desde 2014 (~24 columnas/año). Para tener una base comparable en terminos de fechas, recortaremos la base a ene-2014 para contar con registros quincenales en cada mes.

In [ ]:
long['severidad'].isna().sum()